name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: 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
          TARGET_REPO: hiraras/blog
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
